### ISSUE TITLE
OSA Series 2 Meeting Nov 19th (No meeting Nov 12th)

### ISSUE THREAD

**Issue by mattodd** [opensourceantibiotics/Series-2-Diarylimidazoles#102] opened 2021-11-11 23:38 UTC
_This page is draft until this text is removed._

Meeting Nov 5th 2021 at 2pm UK time at https://ucl.zoom.us/j/92800004715. Follows on from #100  

Recording: 

On the call: 

1. Discussion of which compounds to ship to NEU for ADME data
- There are 12 slots available (LogD, PPB, HLM Clint, rat hepatocyte Clint, aq. sol.)
- @danaklug Analysis below
- @edwintse Clustering?
2. AOB 
- @QSimpson N-alkylated compunds
- Any updates from Lee/Alex?

**PREVIOUS ACTIONS**

- [x] @edwintse to cluster Series 2 compounds and look for candidates for ADME evaluation
- [ ] Alex to discuss DNA binding assays with Gary
- [ ] @MFernflower to capture commercial searching in part of molecule procurement workflow in wiki [here](https://github.com/opensourceantibiotics/Series-2-Diarylimidazoles/wiki/Synthetic-Chemistry#commercial-availability)
- [ ] @QSimpson to see whether an open CDD sheet/vault is Googleable
- [ ] @drc007 to look into solutions for converting master list to something Googleable. Chris has implemented this - he's running something locally that extracts the data, then uses RDkit to create images of structures, then sends that to [this html page](https://opensourceantibiotics.github.io/murligase/CompChemTools/ForIndexing/OSA_data.html) that is on the mur ligase repository. Useful because we can link to it and it should be Googleable. It's not possible to have a Readme up top, so it's important that the sheet contains links for the molecules so that interested viewers know where to go for more. i.e. the OSA Master List needs to include links to where to go for more. @drc007 to check that the current page *is* being searched by Google. If works then we need an action item to consider how best to add "more info" links.

**Comment by drc007** [comment] 2021-11-12 09:24
Ok with me

Chris

**Comment by danaklug** [comment] 2021-11-12 10:23
Food for thought re: NEU ADME assays. 

I thought it might be useful to look at potential candidates in the context of their matched pairs, hopefully this is helpful. Compounds in dotted boxes are ones that we should have stock of at UCL (to be confirmed) and that we don't have any ADME data on yet.

![ADME_11-11-21](https://user-images.githubusercontent.com/53487492/141450987-2116af27-e5b9-4c1f-bca3-307f55bc463e.jpg)

Note that we have ADME data for some additional compounds, but I've based this selection on what's included in the current SAR tables. There are also a few compounds from NEU for which we don't have ADME - for these I've asked @loriferrins if she has this data and can share.  I have not included any compounds from @danielgedder or ones that were donated from DNDi as potential candidates because we don’t have solid stock of them at UCL. However we could consider trying to source more of those if we think it’s important to get ADME data on them.

For me, the four top priority compounds are: 
•	**OSA_1018**: Bridging compound that appears on multiple SAR tables
•	**OSA_987**: Bridging compound that appears on multiple SAR tables
•	**OSA_975**: Compare to OSA_864. Retains the –CN group that appears to result in improved ADME, but is equipotent to OSA_821 and OSA_865. If this compound has a good ADME profile, it could be a frontrunner of the series.
•	**OSA_821**: Would provide a nice bridge between Monash and NEU ADME data.

Other compounds potentially of interest: 
•	**OSA_1011**: Is potent and contains a basic amine
•	**OSA_988**: Completes NH linker table

At this point, my opinion is that it’s not really worth sending anything for ADME with MRSA MIC >4. Happy to have this up for discussion though as we do have room to include some of these with the priority ones.

**Comment by lferrins** [comment] 2021-11-12 12:22
@danaklug this is a really helpful summary, as always! I completely agree with your analysis - you could include 875 if you wanted to (purely based on potency), though I don't anticipate it will be any better/different than 876. I also agree that there isn't a lot of value in getting data on compounds that are >4ug/mL.

I have also emailed the missing ADME data to Dana as this came in earlier in the week.

**Comment by danaklug** [comment] 2021-11-12 13:50
Thanks Lori, new data has been added to the [master sheet](https://docs.google.com/spreadsheets/d/168-a1_l51Nfbms67eG8zU8p-EhEtEO26FUzRInbu7fY/edit#gid=1078638615) and [uploaded](https://github.com/opensourceantibiotics/Series-2-Diarylimidazoles/blob/master/Metabolism/NEU_ADME_11-12-21.csv).

**Comment by edwintse** [comment] 2021-11-19 12:34
Cluster analysis of the Series 2 compounds

- Bottom left cluster (**1**) is the 5,5-core with bicyclic substituents in the NW position
- Bottom middle cluster (**2**) is the 5,5-core with substituted phenyl in the NW position
- Middle cluster (**3**) is the 5,6-core with substituted phenyl in the NW position
- Bottom right cluster (**4**) are the NH-linked 5,6-core compounds
- Top left cluster (**5**) are the N-alkylated 5,6-core compounds
- Small cluster in top right (**6**) are the benzimidazoles (plus a few scattered around the left and bottom left borders)
- Small cluster in the middle left (**7**) are the homologated NH-linked compounds

![Screenshot 2021-11-19 at 12 06 26 pm](https://user-images.githubusercontent.com/18062981/142623550-ed308629-60ab-431e-89b9-ac1dcec59063.png)

**Comment by mattodd** [comment] 2021-11-19 14:31
So, confirming choices
875 for sure.
1018 for sure
987 yes
821 control
1011
988
875 maybe as comparison with 876

Actions
Ed to deploy Datawarrior jedi skills to annotate the fig above to check that these choices are diverse and fill gaps. Though honestly we're pretty well covered on the compounds already!
Mat or Dana to check with Paul S about the next eval round
Quillon to ship new compounds (awesome) though it is holiday season...
Mat to catch up with Lee re MoA
Dana to catch up with Alex re DNA binding experiments (talking to Gary P already).

Nice to see you on camera @MFernflower - first time I think!

**Comment by MFernflower** [comment] 2021-11-19 18:08
@mattodd @QSimpson said there is a new postdoc - maybe if they have time they could make these two compounds???

![image](https://user-images.githubusercontent.com/3164942/142670654-be0ea558-56b7-47c3-a2b8-32bcc26f8f5c.png)

**Comment by danielgedder** [comment] 2022-03-08 18:16
Closing: data incorporated into wiki: https://github.com/opensourceantibiotics/Series-2-Diarylimidazoles/wiki/Metabolic-Clearance-Data

**Closed by danielgedder** 2022-03-08 18:16 UTC
Labels: Meeting
